import type { AnalysisContext, MetricMode } from '../types/dashboard';
import { formatNumber, formatPercent } from '../lib/utils';
import { useDashboardStore } from '../stores/dashboardStore';
import { Button } from '../components/ui/Button';
import { Card, CardHeader } from '../components/ui/Card';

const metricValue = (item: AnalysisContext['categoryStats'][number]['values'][number], metric: MetricMode) => metric === 'share' ? item.share : metric === 'density' ? item.density : item.count;
const label = (value: number | null, metric: MetricMode) => value == null ? 'н/д' : metric === 'share' ? formatPercent(value) : formatNumber.format(value);

export default function CategoriesPage({ context }: { context: AnalysisContext }) {
  const metric = useDashboardStore((state) => state.metric);
  const setMetric = useDashboardStore((state) => state.setMetric);
  return <><div className="page-heading"><div><h1>Категории</h1><p>Все категории текущего среза, медиана peer group и нормирование на подтверждённую GLA.</p></div><div className="segmented">{([['absolute', 'Количество'], ['share', 'Доля'], ['density', 'На 10 000 м² GLA']] as const).map(([id, text]) => <Button key={id} variant={metric === id ? 'default' : 'outline'} onClick={() => setMetric(id)}>{text}</Button>)}</div></div>
    <Card><CardHeader eyebrow="Матрица" title="Heatmap категорий" /><div className="heatmap-scroll"><table className="heatmap"><thead><tr><th>Категория</th>{context.displayMalls.map((mall) => <th key={mall.mall}>{mall.mall}</th>)}</tr></thead><tbody>{context.categoryStats.map((row) => { const numeric = row.values.map((value) => metricValue(value, metric)).filter((value): value is number => value != null); const max = Math.max(1, ...numeric); return <tr key={row.category}><th>{row.category}</th>{row.values.map((value) => { const current = metricValue(value, metric); const alpha = current == null ? 0 : 0.08 + (current / max) * 0.72; return <td key={value.mall} className={value.mall === context.focusMall.mall ? 'heat-focus' : ''} style={{ backgroundColor: current == null ? '#f8fafc' : `rgba(5, 150, 105, ${alpha})` }}>{label(current, metric)}</td>; })}</tr>; })}</tbody></table></div></Card>
    <section className="category-layout"><Card><CardHeader eyebrow="Benchmark" title="Сравнение с медианой" /><div className="bullet-list">{context.categoryStats.map((item) => { const focus = metric === 'absolute' ? item.focus.count : metric === 'share' ? item.focus.share : item.focus.density; const median = metric === 'absolute' ? item.countMedian : metric === 'share' ? item.shareMedian : item.densityMedian; const values = item.values.map((value) => metricValue(value, metric)).filter((value): value is number => value != null); const max = Math.max(1, ...values); return <div className="bullet-row" key={item.category}><span>{item.category}</span><div className="bullet-track"><i className="bullet-focus" style={{ width: `${(focus ?? 0) / max * 100}%` }} /><i className="bullet-median" style={{ left: `${(median ?? 0) / max * 100}%` }} /></div><b>{label(focus, metric)} / {label(median, metric)}</b></div>; })}</div></Card>
      <Card><CardHeader eyebrow="Область расчёта" title="Уникальность и пересечения" /><div className="uniqueness-table"><div><span>Уникальные во всей базе</span><b>{context.uniqueness.global.size}</b><small>Все объекты базы</small></div><div><span>Уникальные в группе</span><b>{context.uniqueness.group.size}</b><small>{context.uniqueness.scopeLabel}</small></div><div><span>Эксклюзивы фокусного ТЦ</span><b>{context.uniqueness.focusExclusive.size}</b><small>Текущая группа</small></div><div><span>Пересекающиеся</span><b>{context.intersections.intersecting.size}</b><small>Текущая группа</small></div></div></Card></section></>;
}
