import type { AnalysisContext, MetricMode } from '../types/dashboard';
import { formatNumber, formatPercent } from '../lib/utils';
import { useDashboardStore } from '../stores/dashboardStore';
import { Button } from '../components/ui/Button';
import { Card, CardHeader } from '../components/ui/Card';

const metricValue = (item: AnalysisContext['categoryStats'][number]['values'][number], metric: MetricMode) => metric === 'share' ? item.share : metric === 'density' ? item.density : item.count;
const label = (value: number | null, metric: MetricMode) => value == null ? 'н/д' : metric === 'share' ? formatPercent(value) : formatNumber.format(value);
const medianValue = (item: AnalysisContext['categoryStats'][number], metric: MetricMode) => metric === 'share' ? item.shareMedian : metric === 'density' ? item.densityMedian : item.countMedian;
const heatColor = (value: number | null, max: number) => {
  if (value == null) return '#f8fafc';
  const ratio = Math.max(0, Math.min(1, value / Math.max(max, Number.EPSILON)));
  const lightness = 96 - ratio * 48;
  return `hsl(158 76% ${lightness}%)`;
};

export default function CategoriesPage({ context }: { context: AnalysisContext }) {
  const metric = useDashboardStore((state) => state.metric);
  const setMetric = useDashboardStore((state) => state.setMetric);
  const allValues = context.categoryStats.flatMap((row) => row.values.map((value) => metricValue(value, metric))).filter((value): value is number => value != null);
  const scaleMax = Math.max(Number.EPSILON, ...allValues);
  return <><div className="page-heading"><div><h1>Категории</h1><p>Все категории текущего среза, медиана группы сравнения и нормирование на подтверждённую GLA.</p></div><div className="segmented">{([['absolute', 'Количество'], ['share', 'Доля'], ['density', 'На 10 000 м² GLA']] as const).map(([id, text]) => <Button key={id} variant={metric === id ? 'default' : 'outline'} onClick={() => setMetric(id)}>{text}</Button>)}</div></div>
    <Card><CardHeader eyebrow="Матрица" title="Heatmap категорий" />
      <div className="heatmap-legend" aria-label="Шкала интенсивности"><span>Ниже</span><i /><span>Выше</span><small>Единая шкала для всех строк в режиме «{metric === 'absolute' ? 'Количество' : metric === 'share' ? 'Доля' : 'На 10 000 м² GLA'}»</small></div>
      <div className="heatmap-scroll category-heatmap-desktop"><table className="heatmap"><thead><tr><th>Категория</th>{context.displayMalls.map((mall) => <th key={mall.mall}>{mall.mall}</th>)}</tr></thead><tbody>{context.categoryStats.map((row) => <tr key={row.category}><th>{row.category}</th>{row.values.map((value) => { const current = metricValue(value, metric); const ratio = current == null ? 0 : current / scaleMax; return <td key={value.mall} className={value.mall === context.focusMall.mall ? 'heat-focus' : ''} style={{ backgroundColor: heatColor(current, scaleMax), color: ratio > 0.62 ? '#ffffff' : '#0f172a' }}>{label(current, metric)}</td>; })}</tr>)}</tbody></table></div>
      <div className="category-heatmap-mobile" aria-label="Сравнение категорий фокусного объекта с медианой группы">{context.categoryStats.map((item) => { const focus = metricValue(item.focus, metric); const median = medianValue(item, metric); const values = item.values.map((value) => metricValue(value, metric)).filter((value): value is number => value != null); const max = Math.max(Number.EPSILON, ...values, focus ?? 0, median ?? 0); const focusWidth = focus == null ? 0 : Math.min(100, (focus / max) * 100); const medianLeft = median == null ? null : Math.min(100, (median / max) * 100); const delta = focus == null || median == null ? null : focus - median; const status = delta == null ? 'neutral' : delta > 0 ? 'positive' : delta < 0 ? 'negative' : 'neutral'; return <article className="category-mobile-row" key={item.category}><header><strong>{item.category}</strong><span className={`category-mobile-delta ${status}`}>{delta == null ? 'н/д' : `${delta > 0 ? '+' : ''}${label(delta, metric)}`}</span></header><div className="category-mobile-values"><div><small>{context.focusMall.mall}</small><b>{label(focus, metric)}</b></div><div><small>Медиана группы</small><b>{label(median, metric)}</b></div></div><div className="category-mobile-track" aria-hidden="true"><i className="category-mobile-focus" style={{ width: `${focusWidth}%` }} />{medianLeft != null && <i className="category-mobile-median" style={{ left: `${medianLeft}%` }} />}</div></article>; })}</div>
    </Card>
    <section className="category-layout"><Card><CardHeader eyebrow="Benchmark" title="Сравнение с медианой" /><div className="bullet-list">{context.categoryStats.map((item) => { const focus = metric === 'absolute' ? item.focus.count : metric === 'share' ? item.focus.share : item.focus.density; const median = metric === 'absolute' ? item.countMedian : metric === 'share' ? item.shareMedian : item.densityMedian; const values = item.values.map((value) => metricValue(value, metric)).filter((value): value is number => value != null); const max = Math.max(Number.EPSILON, ...values); return <div className="bullet-row" key={item.category}><span>{item.category}</span><div className="bullet-track"><i className="bullet-focus" style={{ width: `${(focus ?? 0) / max * 100}%` }} /><i className="bullet-median" style={{ left: `${(median ?? 0) / max * 100}%` }} /></div><b>{label(focus, metric)} / {label(median, metric)}</b></div>; })}</div></Card>
      <Card><CardHeader eyebrow="Область расчёта" title="Уникальность и пересечения" /><div className="uniqueness-table"><div><span>Уникальные во всей базе</span><b>{context.uniqueness.global.size}</b><small>Все объекты базы</small></div><div><span>Уникальные в группе</span><b>{context.uniqueness.group.size}</b><small>{context.uniqueness.scopeLabel}</small></div><div><span>Эксклюзивы фокусного объекта</span><b>{context.uniqueness.focusExclusive.size}</b><small>Текущая группа</small></div><div><span>Пересекающиеся</span><b>{context.intersections.intersecting.size}</b><small>Текущая группа</small></div></div></Card></section></>;
}
