import { Plus, Save, Trash2 } from 'lucide-react';
import { useMemo, useState } from 'react';
import type { AnalysisContext, DashboardData } from '../types/dashboard';
import { useScenarioStore } from '../stores/scenarioStore';
import { Button } from '../components/ui/Button';
import { Card, CardHeader } from '../components/ui/Card';

export default function ScenariosPage({ context, data }: { context: AnalysisContext; data: DashboardData }) {
  const [added, setAdded] = useState<string[]>([]); const [removed, setRemoved] = useState<string[]>([]); const [brand, setBrand] = useState('');
  const { scenarios, save, remove } = useScenarioStore();
  const focusKeys = context.intersections.focusBrands;
  const candidates = useMemo(() => Object.values(data.brandPresence).filter((item) => !focusKeys.has(item.brandNormalized)).slice(0, 500), [data, focusKeys]);
  const baseline = context.benchmark.focusBrandCount; const scenarioTotal = baseline + added.length - removed.length;
  const saveCurrent = () => save({ id: crypto.randomUUID(), name: `Сценарий ${scenarios.length + 1}`, focusMallId: context.focusMall.mall, createdAt: new Date().toISOString(), dataSnapshot: data.meta.snapshotDate, addedBrandIds: added, removedBrandIds: removed, schemaVersion: 1 });
  return <><div className="page-heading"><div><h1>Сценарии</h1><p>Аналитический sandbox. Изменения не затрагивают production-базу и не рассчитывают финансовый эффект.</p></div><Button onClick={saveCurrent}><Save size={17} />Сохранить</Button></div><section className="scenario-grid"><Card><CardHeader eyebrow="Baseline vs scenario" title={context.focusMall.mall} /><div className="scenario-kpis"><div><span>Baseline</span><b>{baseline}</b></div><div><span>Scenario</span><b>{scenarioTotal}</b></div><div><span>Изменение</span><b>{scenarioTotal - baseline > 0 ? '+' : ''}{scenarioTotal - baseline}</b></div></div><label className="scenario-add">Добавить бренд<select value={brand} onChange={(event) => setBrand(event.target.value)}><option value="">Выберите бренд</option>{candidates.map((item) => <option key={item.brandNormalized} value={item.brandNormalized}>{item.brand} · {item.category}</option>)}</select><Button disabled={!brand} onClick={() => { if (brand && !added.includes(brand)) setAdded([...added, brand]); setBrand(''); }}><Plus size={17} />Добавить</Button></label><div className="scenario-changes"><h3>Добавлены</h3>{added.map((key) => <button key={key} onClick={() => setAdded(added.filter((item) => item !== key))}>{data.brandPresence[key]?.brand ?? key}<Trash2 size={14} /></button>)}<h3>Удалены</h3>{[...focusKeys].slice(0, 20).map((key) => <label key={key}><input type="checkbox" checked={removed.includes(key)} onChange={() => setRemoved(removed.includes(key) ? removed.filter((item) => item !== key) : [...removed, key])} />{data.brandPresence[key]?.brand ?? key}</label>)}</div></Card><Card><CardHeader eyebrow="LocalStorage" title="Сохранённые сценарии" /><div className="saved-scenarios">{scenarios.map((item) => <div key={item.id}><div><strong>{item.name}</strong><small>{item.focusMallId} · {item.dataSnapshot} · +{item.addedBrandIds.length} / -{item.removedBrandIds.length}</small></div><Button variant="ghost" onClick={() => remove(item.id)} aria-label={`Удалить ${item.name}`}><Trash2 size={16} /></Button></div>)}{!scenarios.length ? <p className="empty-state">Сохранённых сценариев пока нет.</p> : null}</div></Card></section></>;
}
