(function(ns){
  const A=()=>ns.analytics;const labels={superregional:'Суперрегиональные',regional:'Региональные',district:'Районные','no-area':'Нет данных по площади',nn:'Нижний Новгород',moscow:'Москва',spb:'Санкт-Петербург',regions:'Регионы'};
  function options(values,current){return values.map(([value,label])=>`<option value="${value}" ${value===current?'selected':''}>${label}</option>`).join('');}
  function init(state){
    const malls=A().data.mallSummary.map(item=>item.mall).sort((a,b)=>a.localeCompare(b,'ru'));
    document.getElementById('focusSelect').innerHTML=options(malls.map(m=>[m,m]),state.focus);
    document.getElementById('groupSelect').innerHTML=options([['superregional','Суперрегиональные'],['regional','Региональные'],['district','Районные'],['all','Все форматы']],state.groups.length===1?state.groups[0]:'all');
    document.getElementById('geoSelect').innerHTML=options([['nn-regions','НН и регионы'],['nn','Нижний Новгород'],['regions','Регионы'],['moscow','Москва'],['spb','Санкт-Петербург'],['all','Вся Россия']],state.geos.join('-'));
    document.getElementById('categorySelect').innerHTML=options([['Все категории','Все категории'],...A().data.categoryMatrix.categories.map(c=>[c,c])],state.category);
    renderTags(state);renderDrawer(state);
  }
  function renderTags(state){const tags=[];state.groups.forEach(id=>tags.push([`group:${id}`,labels[id]||id]));state.geos.forEach(id=>tags.push([`geo:${id}`,labels[id]||id]));if(state.category!=='Все категории')tags.push(['category',state.category]);if(state.selectedMalls.length)tags.push(['malls',`${state.selectedMalls.length} ТЦ`]);if(state.qualities.length)tags.push(['quality',`Источники: ${state.qualities.join(', ')}`]);document.getElementById('activeTags').innerHTML=tags.map(([id,label])=>`<span class="tag">${label}<button type="button" data-remove-tag="${id}" aria-label="Удалить фильтр ${label}">×</button></span>`).join('');}
  function checkboxList(name,values,selected){return `<div class="check-list">${values.map(value=>`<label class="check-item"><input type="checkbox" name="${name}" value="${value}" ${selected.includes(value)?'checked':''}><span>${value}</span></label>`).join('')}</div>`;}
  function multiSelect(id,label,values,selected,valueKey=value=>value,labelKey=value=>value){return `<label class="drawer-section"><h3>${label}</h3><select id="${id}" class="multi-select" multiple size="7" aria-label="${label}">${values.map(value=>{const key=valueKey(value);return `<option value="${key}" ${selected.includes(key)?'selected':''}>${labelKey(value)}</option>`}).join('')}</select><span class="panel-note">Ctrl/Cmd или Shift для выбора нескольких значений</span></label>`;}
  function renderDrawer(state){const cities=[...new Set(A().data.mallSummary.map(m=>m.city))].sort((a,b)=>a.localeCompare(b,'ru'));const malls=A().data.mallSummary.map(m=>m.mall).sort((a,b)=>a.localeCompare(b,'ru'));const brands=Object.values(A().data.brandPresence).sort((a,b)=>a.brand.localeCompare(b.brand,'ru'));const tenants=[...new Set(A().data.rows.map(row=>row.brand))].sort((a,b)=>a.localeCompare(b,'ru'));const sourceTypes=[...new Set(A().data.rows.map(row=>row.sourceType))].sort((a,b)=>a.localeCompare(b,'ru'));document.getElementById('drawerBody').innerHTML=`
    <section class="drawer-section"><h3>GLA, м²</h3><div class="range-grid"><input id="glaMin" type="number" min="0" placeholder="от" value="${state.glaMin??''}" aria-label="Минимальная GLA"><input id="glaMax" type="number" min="0" placeholder="до" value="${state.glaMax??''}" aria-label="Максимальная GLA"></div></section>
    <section class="drawer-section"><h3>GBA, м²</h3><div class="range-grid"><input id="gbaMin" type="number" min="0" placeholder="от" value="${state.gbaMin??''}" aria-label="Минимальная GBA"><input id="gbaMax" type="number" min="0" placeholder="до" value="${state.gbaMax??''}" aria-label="Максимальная GBA"></div></section>
    <section class="drawer-section"><h3>Города</h3>${checkboxList('city',cities,state.cities)}</section>
    <section class="drawer-section"><h3>Конкретные ТЦ</h3>${checkboxList('mall',malls,state.selectedMalls)}</section>
    ${multiSelect('brandFilter','Бренды',brands,state.brands,value=>value.brandNormalized,value=>value.brand)}
    ${multiSelect('tenantFilter','Арендаторы',tenants,state.tenants)}
    ${multiSelect('sourceTypeFilter','Тип источника',sourceTypes,state.sourceTypes)}
    <section class="drawer-section"><h3>Достоверность источника</h3>${checkboxList('quality',['Высокая','Средняя','Низкая'],state.qualities)}</section>
    <section class="drawer-section"><h3>Статус будущего открытия</h3>${checkboxList('upcomingStatus',[...new Set(A().data.upcoming.map(item=>item.status))],state.upcomingStatuses)}</section>`;}
  function readDrawer(state){const checked=name=>[...document.querySelectorAll(`#drawerBody input[name="${name}"]:checked`)].map(el=>el.value);const selected=id=>[...document.getElementById(id).selectedOptions].map(option=>option.value);const num=id=>{const value=document.getElementById(id).value;return value===''?null:Number(value)};return{...state,cities:checked('city'),selectedMalls:checked('mall'),brands:selected('brandFilter'),tenants:selected('tenantFilter'),sourceTypes:selected('sourceTypeFilter'),qualities:checked('quality'),upcomingStatuses:checked('upcomingStatus'),glaMin:num('glaMin'),glaMax:num('glaMax'),gbaMin:num('gbaMin'),gbaMax:num('gbaMax')};}
  function openDrawer(open){const drawer=document.getElementById('filterDrawer');drawer.classList.toggle('open',open);drawer.setAttribute('aria-hidden',String(!open));drawer.toggleAttribute('inert',!open);document.getElementById('moreFilters').setAttribute('aria-expanded',String(open));document.getElementById('scrim').hidden=!open;if(open)setTimeout(()=>document.getElementById('closeDrawer').focus(),20);}
  ns.filters={init,renderTags,renderDrawer,readDrawer,openDrawer,labels};
})(window.TenantMixV2=window.TenantMixV2||{});
