(function(ns){
  const local={search:'',mall:'',category:'',quality:'',sort:'brand',direction:1,rows:[],filtered:[],rowHeight:54};let debounceTimer;
  function escapeCsv(value){const text=String(value??'');return /[";,\n]/.test(text)?`"${text.replaceAll('"','""')}"`:text;}
  function apply(){const q=local.search.toLocaleLowerCase('ru');local.filtered=local.rows.filter(row=>(!q||`${row.brand} ${row.brandNormalized} ${row.mall} ${row.category}`.toLocaleLowerCase('ru').includes(q))&&(!local.mall||row.mall===local.mall)&&(!local.category||row.category===local.category)&&(!local.quality||row.sourceQuality===local.quality));local.filtered.sort((a,b)=>String(a[local.sort]||'').localeCompare(String(b[local.sort]||''),'ru')*local.direction);renderBody();document.getElementById('tenantCount').textContent=`${ns.analytics.fmt.format(local.filtered.length)} строк`}
  function render(ctx){local.rows=ctx.rows;const malls=[...new Set(local.rows.map(r=>r.mall))].sort((a,b)=>a.localeCompare(b,'ru'));const categories=[...new Set(local.rows.map(r=>r.category))].sort((a,b)=>a.localeCompare(b,'ru'));return `<div class="table-layout"><div class="table-toolbar"><div><input class="search" id="tenantSearch" type="search" placeholder="Поиск бренда, ТЦ или категории" aria-label="Поиск в реестре"><span class="muted" id="tenantCount"></span></div><div><select id="tenantMall" aria-label="Фильтр по ТЦ"><option value="">Все ТЦ</option>${malls.map(v=>`<option>${v}</option>`).join('')}</select><select id="tenantCategory" aria-label="Фильтр по категории"><option value="">Все категории</option>${categories.map(v=>`<option>${v}</option>`).join('')}</select><select id="tenantQuality" aria-label="Фильтр качества источника"><option value="">Все источники</option><option>Высокая</option><option>Средняя</option><option>Низкая</option></select><button class="button secondary" id="exportCsv">Экспорт CSV</button><button class="button ghost" id="resetTenantFilters">Сбросить</button></div></div><div class="data-table"><div class="table-header" role="row"><div>Бренд</div><div>ТЦ</div><div>Категория</div><div>Источник</div><div>Подтверждение</div></div><div class="virtual-table" id="tenantViewport" tabindex="0" aria-label="Реестр арендаторов"><div class="virtual-spacer" id="tenantSpacer"></div></div></div></div>`;}
  function rowHtml(row,index,top){const qualityClass=row.sourceQuality==='Высокая'?'high':row.sourceQuality==='Средняя'?'medium':'low';return `<div class="table-row" role="row" style="transform:translateY(${top}px)" data-index="${index}"><div class="cell-ellipsis"><button class="button ghost" data-open-brand="${row.brandNormalized}">${row.brand}</button></div><div class="cell-ellipsis">${row.mall}</div><div>${row.category}</div><div>${row.sourceUrl?`<a class="source-link" href="${row.sourceUrl}" target="_blank" rel="noopener">Источник ↗</a>`:'Без ссылки'}</div><div><span class="quality ${qualityClass}">${row.sourceQuality}</span><br><small>${row.checkedAt}</small></div></div>`;}
  function renderBody(){const viewport=document.getElementById('tenantViewport');const spacer=document.getElementById('tenantSpacer');if(!viewport||!spacer)return;const mobile=matchMedia('(max-width:620px)').matches;if(mobile){const shown=local.filtered.slice(0,180);spacer.style.height='auto';spacer.innerHTML=shown.map((row,index)=>rowHtml(row,index,0)).join('');return}const start=Math.max(0,Math.floor(viewport.scrollTop/local.rowHeight)-6);const visible=Math.ceil(viewport.clientHeight/local.rowHeight)+12;const end=Math.min(local.filtered.length,start+visible);spacer.style.height=`${local.filtered.length*local.rowHeight}px`;spacer.innerHTML=local.filtered.slice(start,end).map((row,index)=>rowHtml(row,start+index,(start+index)*local.rowHeight)).join('');}
  function bind(){const search=document.getElementById('tenantSearch');search.addEventListener('input',()=>{clearTimeout(debounceTimer);debounceTimer=setTimeout(()=>{local.search=search.value;apply()},200)});[['tenantMall','mall'],['tenantCategory','category'],['tenantQuality','quality']].forEach(([id,key])=>document.getElementById(id).addEventListener('change',event=>{local[key]=event.target.value;apply()}));document.getElementById('tenantViewport').addEventListener('scroll',renderBody);document.getElementById('resetTenantFilters').addEventListener('click',()=>{local.search=local.mall=local.category=local.quality='';['tenantSearch','tenantMall','tenantCategory','tenantQuality'].forEach(id=>document.getElementById(id).value='');apply()});document.getElementById('exportCsv').addEventListener('click',exportCsv);apply();}
  function exportCsv(){const header=['Бренд','Нормализованный бренд','ТЦ','Категория','Источник','URL','Качество','Проверено'];const lines=[header,...local.filtered.map(row=>[row.brand,row.brandNormalized,row.mall,row.category,row.sourceType,row.sourceUrl,row.sourceQuality,row.checkedAt])].map(row=>row.map(escapeCsv).join(';')).join('\n');const blob=new Blob(['\ufeff'+lines],{type:'text/csv;charset=utf-8'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='tenant-mix-filtered.csv';link.click();URL.revokeObjectURL(link.href);}
  ns.tenantTable={render,bind,apply,local};
})(window.TenantMixV2=window.TenantMixV2||{});
